// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personModel.proto

package com.example.design.model;

public final class PersonModel {
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_model_Person_descriptor;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_model_Person_PhoneNumber_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_model_Person_fieldAccessorTable;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_model_Person_PhoneNumber_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;

  static {
    String[] descriptorData = {
            "\n\021personModel.proto\022\005model\"\324\001\n\006Person\022\014\n"
                    + "\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\005\022\r\n\005email\030\003 \001(\t\022("
                    + "\n\005phone\030\004 \003(\0132\031.model.Person.PhoneNumber"
                    + "\032J\n\013PhoneNumber\022\016\n\006number\030\001 \002(\t\022+\n\004type\030"
                    + "\002 \001(\0162\027.model.Person.PhoneType:\004HOME\"+\n\t"
                    + "PhoneType\022\n\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020"
                    + "\002B\'\n\030com.example.design.modelB\013PersonMod"
                    + "el"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            root -> {
              descriptor = root;
              return null;
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[]{
                    }, assigner);
    internal_static_model_Person_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_model_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_model_Person_descriptor,
            new String[]{"Name", "Id", "Email", "Phone",});
    internal_static_model_Person_PhoneNumber_descriptor =
            internal_static_model_Person_descriptor.getNestedTypes().get(0);
    internal_static_model_Person_PhoneNumber_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_model_Person_PhoneNumber_descriptor,
            new String[]{"Number", "Type",});
  }

  private PersonModel() {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }

  public interface PersonOrBuilder extends
          // @@protoc_insertion_point(interface_extends:model.Person)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();

    /**
     * <code>required string name = 1;</code>
     */
    String getName();

    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>required int32 id = 2;</code>
     */
    boolean hasId();

    /**
     * <code>required int32 id = 2;</code>
     */
    int getId();

    /**
     * <code>optional string email = 3;</code>
     */
    boolean hasEmail();

    /**
     * <code>optional string email = 3;</code>
     */
    String getEmail();

    /**
     * <code>optional string email = 3;</code>
     */
    com.google.protobuf.ByteString
    getEmailBytes();

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    java.util.List<Person.PhoneNumber>
    getPhoneList();

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    Person.PhoneNumber getPhone(int index);

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    int getPhoneCount();

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    java.util.List<? extends Person.PhoneNumberOrBuilder>
    getPhoneOrBuilderList();

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    Person.PhoneNumberOrBuilder getPhoneOrBuilder(
            int index);
  }

  /**
   * Protobuf type {@code model.Person}
   */
  public static final class Person extends
          com.google.protobuf.GeneratedMessage implements
          // @@protoc_insertion_point(message_implements:model.Person)
          PersonOrBuilder {
    public static final int NAME_FIELD_NUMBER = 1;
    public static final int ID_FIELD_NUMBER = 2;
    public static final int EMAIL_FIELD_NUMBER = 3;
    public static final int PHONE_FIELD_NUMBER = 4;
    private static final Person defaultInstance;
    private static final long serialVersionUID = 0L;
    public static com.google.protobuf.Parser<Person> PARSER =
            new com.google.protobuf.AbstractParser<Person>() {
              public Person parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new Person(input, extensionRegistry);
              }
            };

    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    private int bitField0_;
    private Object name_;
    private int id_;
    private Object email_;
    private java.util.List<PhoneNumber> phone_;
    private byte memoizedIsInitialized = -1;
    private int memoizedSerializedSize = -1;

    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }

    private Person(boolean noInit) {
      this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private Person(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              email_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                phone_ = new java.util.ArrayList<PhoneNumber>();
                mutable_bitField0_ |= 0x00000008;
              }
              phone_.add(input.readMessage(PhoneNumber.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return PersonModel.internal_static_model_Person_descriptor;
    }

    public static Person parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Person parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Person parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Person parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Person parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static Person parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Person parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }

    public static Person parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }

    public static Person parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }

    public static Person parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return Builder.create();
    }

    public static Builder newBuilder(Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return PersonModel.internal_static_model_Person_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      Person.class, Builder.class);
    }

    @Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }

    /**
     * <code>required string name = 1;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>required int32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }

    /**
     * <code>required int32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    /**
     * <code>optional string email = 3;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }

    /**
     * <code>optional string email = 3;</code>
     */
    public String getEmail() {
      Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string email = 3;</code>
     */
    public com.google.protobuf.ByteString
    getEmailBytes() {
      Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    public java.util.List<PhoneNumber> getPhoneList() {
      return phone_;
    }

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    public java.util.List<? extends PhoneNumberOrBuilder>
    getPhoneOrBuilderList() {
      return phone_;
    }

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    public int getPhoneCount() {
      return phone_.size();
    }

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    public PhoneNumber getPhone(int index) {
      return phone_.get(index);
    }

    /**
     * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
     */
    public PhoneNumberOrBuilder getPhoneOrBuilder(
            int index) {
      return phone_.get(index);
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      email_ = "";
      phone_ = java.util.Collections.emptyList();
    }

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPhoneCount(); i++) {
        if (!getPhone(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        output.writeMessage(4, phone_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, getEmailBytes());
      }
      for (int i = 0; i < phone_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(4, phone_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    @Override
    protected Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public Builder toBuilder() {
      return newBuilder(this);
    }

    @Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf enum {@code model.Person.PhoneType}
     */
    public enum PhoneType
            implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILE = 0;</code>
       */
      MOBILE(0, 0),
      /**
       * <code>HOME = 1;</code>
       */
      HOME(1, 1),
      /**
       * <code>WORK = 2;</code>
       */
      WORK(2, 2),;

      /**
       * <code>MOBILE = 0;</code>
       */
      public static final int MOBILE_VALUE = 0;
      /**
       * <code>HOME = 1;</code>
       */
      public static final int HOME_VALUE = 1;
      /**
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;
      private static final PhoneType[] VALUES = values();
      private static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
              internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                public PhoneType findValueByNumber(int number) {
                  return PhoneType.valueOf(number);
                }
              };
      private final int index;
      private final int value;

      private PhoneType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      public static PhoneType valueOf(int value) {
        switch (value) {
          case 0:
            return MOBILE;
          case 1:
            return HOME;
          case 2:
            return WORK;
          default:
            return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
      internalGetValueMap() {
        return internalValueMap;
      }

      public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
        return Person.getDescriptor().getEnumTypes().get(0);
      }

      public static PhoneType valueOf(
              com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
                  "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      public final int getNumber() {
        return value;
      }

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }

      public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
        return getDescriptor();
      }

      // @@protoc_insertion_point(enum_scope:model.Person.PhoneType)
    }

    public interface PhoneNumberOrBuilder extends
            // @@protoc_insertion_point(interface_extends:model.Person.PhoneNumber)
            com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string number = 1;</code>
       */
      boolean hasNumber();

      /**
       * <code>required string number = 1;</code>
       */
      String getNumber();

      /**
       * <code>required string number = 1;</code>
       */
      com.google.protobuf.ByteString
      getNumberBytes();

      /**
       * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
       */
      boolean hasType();

      /**
       * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
       */
      PhoneType getType();
    }

    /**
     * Protobuf type {@code model.Person.PhoneNumber}
     */
    public static final class PhoneNumber extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:model.Person.PhoneNumber)
            PhoneNumberOrBuilder {
      public static final int NUMBER_FIELD_NUMBER = 1;
      public static final int TYPE_FIELD_NUMBER = 2;
      private static final PhoneNumber defaultInstance;
      private static final long serialVersionUID = 0L;
      public static com.google.protobuf.Parser<PhoneNumber> PARSER =
              new com.google.protobuf.AbstractParser<PhoneNumber>() {
                public PhoneNumber parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                  return new PhoneNumber(input, extensionRegistry);
                }
              };

      static {
        defaultInstance = new PhoneNumber(true);
        defaultInstance.initFields();
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      private int bitField0_;
      private Object number_;
      private PhoneType type_;
      private byte memoizedIsInitialized = -1;
      private int memoizedSerializedSize = -1;

      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }

      private PhoneNumber(boolean noInit) {
        this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }

      private PhoneNumber(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                        extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                number_ = bs;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();
                PhoneType value = PhoneType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(2, rawValue);
                } else {
                  bitField0_ |= 0x00000002;
                  type_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }

      public static PhoneNumber getDefaultInstance() {
        return defaultInstance;
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return PersonModel.internal_static_model_Person_PhoneNumber_descriptor;
      }

      public static PhoneNumber parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static PhoneNumber parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static PhoneNumber parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static PhoneNumber parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static PhoneNumber parseFrom(java.io.InputStream input)
              throws java.io.IOException {
        return PARSER.parseFrom(input);
      }

      public static PhoneNumber parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static PhoneNumber parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }

      public static PhoneNumber parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }

      public static PhoneNumber parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
        return PARSER.parseFrom(input);
      }

      public static PhoneNumber parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return Builder.create();
      }

      public static Builder newBuilder(PhoneNumber prototype) {
        return newBuilder().mergeFrom(prototype);
      }

      public PhoneNumber getDefaultInstanceForType() {
        return defaultInstance;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return PersonModel.internal_static_model_Person_PhoneNumber_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        PhoneNumber.class, Builder.class);
      }

      @Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      /**
       * <code>required string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /**
       * <code>required string number = 1;</code>
       */
      public String getNumber() {
        Object ref = number_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        }
      }

      /**
       * <code>required string number = 1;</code>
       */
      public com.google.protobuf.ByteString
      getNumberBytes() {
        Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /**
       * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
       */
      public PhoneType getType() {
        return type_;
      }

      private void initFields() {
        number_ = "";
        type_ = PhoneType.HOME;
      }

      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasNumber()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeEnum(2, type_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeBytesSize(1, getNumberBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeEnumSize(2, type_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      @Override
      protected Object writeReplace()
              throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public Builder newBuilderForType() {
        return newBuilder();
      }

      public Builder toBuilder() {
        return newBuilder(this);
      }

      @Override
      protected Builder newBuilderForType(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }

      /**
       * Protobuf type {@code model.Person.PhoneNumber}
       */
      public static final class Builder extends
              com.google.protobuf.GeneratedMessage.Builder<Builder> implements
              // @@protoc_insertion_point(builder_implements:model.Person.PhoneNumber)
              PhoneNumberOrBuilder {
        private int bitField0_;
        private Object number_ = "";
        private PhoneType type_ = PhoneType.HOME;

        // Construct using com.example.design.model.PersonModel.Person.PhoneNumber.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
          return PersonModel.internal_static_model_Person_PhoneNumber_descriptor;
        }

        private static Builder create() {
          return new Builder();
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
          return PersonModel.internal_static_model_Person_PhoneNumber_fieldAccessorTable
                  .ensureFieldAccessorsInitialized(
                          PhoneNumber.class, Builder.class);
        }

        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }

        public Builder clear() {
          super.clear();
          number_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = PhoneType.HOME;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
          return PersonModel.internal_static_model_Person_PhoneNumber_descriptor;
        }

        public PhoneNumber getDefaultInstanceForType() {
          return PhoneNumber.getDefaultInstance();
        }

        public PhoneNumber build() {
          PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public PhoneNumber buildPartial() {
          PhoneNumber result = new PhoneNumber(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.number_ = number_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PhoneNumber) {
            return mergeFrom((PhoneNumber) other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PhoneNumber other) {
          if (other == PhoneNumber.getDefaultInstance()) return this;
          if (other.hasNumber()) {
            bitField0_ |= 0x00000001;
            number_ = other.number_;
            onChanged();
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasNumber()) {

            return false;
          }
          return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
          PhoneNumber parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (PhoneNumber) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        /**
         * <code>required string number = 1;</code>
         */
        public boolean hasNumber() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string number = 1;</code>
         */
        public String getNumber() {
          Object ref = number_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              number_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }

        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumber(
                String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>required string number = 1;</code>
         */
        public com.google.protobuf.ByteString
        getNumberBytes() {
          Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        /**
         * <code>required string number = 1;</code>
         */
        public Builder setNumberBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          number_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>required string number = 1;</code>
         */
        public Builder clearNumber() {
          bitField0_ = (bitField0_ & ~0x00000001);
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }

        /**
         * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public PhoneType getType() {
          return type_;
        }

        /**
         * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder setType(PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          type_ = value;
          onChanged();
          return this;
        }

        /**
         * <code>optional .model.Person.PhoneType type = 2 [default = HOME];</code>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = PhoneType.HOME;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:model.Person.PhoneNumber)
      }

      // @@protoc_insertion_point(class_scope:model.Person.PhoneNumber)
    }

    /**
     * Protobuf type {@code model.Person}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:model.Person)
            PersonOrBuilder {
      private int bitField0_;
      private Object name_ = "";
      private int id_;
      private Object email_ = "";
      private java.util.List<PhoneNumber> phone_ =
              java.util.Collections.emptyList();
      private com.google.protobuf.RepeatedFieldBuilder<
              PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder> phoneBuilder_;

      // Construct using com.example.design.model.PersonModel.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return PersonModel.internal_static_model_Person_descriptor;
      }

      private static Builder create() {
        return new Builder();
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return PersonModel.internal_static_model_Person_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Person.class, Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPhoneFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return PersonModel.internal_static_model_Person_descriptor;
      }

      public Person getDefaultInstanceForType() {
        return Person.getDefaultInstance();
      }

      public Person build() {
        Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person buildPartial() {
        Person result = new Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (phoneBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            phone_ = java.util.Collections.unmodifiableList(phone_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.phone_ = phone_;
        } else {
          result.phone_ = phoneBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person) {
          return mergeFrom((Person) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person other) {
        if (other == Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          bitField0_ |= 0x00000004;
          email_ = other.email_;
          onChanged();
        }
        if (phoneBuilder_ == null) {
          if (!other.phone_.isEmpty()) {
            if (phone_.isEmpty()) {
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensurePhoneIsMutable();
              phone_.addAll(other.phone_);
            }
            onChanged();
          }
        } else {
          if (!other.phone_.isEmpty()) {
            if (phoneBuilder_.isEmpty()) {
              phoneBuilder_.dispose();
              phoneBuilder_ = null;
              phone_ = other.phone_;
              bitField0_ = (bitField0_ & ~0x00000008);
              phoneBuilder_ =
                      com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                              getPhoneFieldBuilder() : null;
            } else {
              phoneBuilder_.addAllMessages(other.phone_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {

          return false;
        }
        if (!hasId()) {

          return false;
        }
        for (int i = 0; i < getPhoneCount(); i++) {
          if (!getPhone(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }

      /**
       * <code>required string name = 1;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }

      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }

      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required int32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>optional string email = 3;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }

      /**
       * <code>optional string email = 3;</code>
       */
      public String getEmail() {
        Object ref = email_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            email_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }

      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmail(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string email = 3;</code>
       */
      public com.google.protobuf.ByteString
      getEmailBytes() {
        Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string email = 3;</code>
       */
      public Builder setEmailBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string email = 3;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }

      private void ensurePhoneIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          phone_ = new java.util.ArrayList<PhoneNumber>(phone_);
          bitField0_ |= 0x00000008;
        }
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public java.util.List<PhoneNumber> getPhoneList() {
        if (phoneBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phone_);
        } else {
          return phoneBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public int getPhoneCount() {
        if (phoneBuilder_ == null) {
          return phone_.size();
        } else {
          return phoneBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public PhoneNumber getPhone(int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(
              int index, PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.set(index, value);
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder setPhone(
              int index, PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
              int index, PhoneNumber value) {
        if (phoneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneIsMutable();
          phone_.add(index, value);
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
              PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder addPhone(
              int index, PhoneNumber.Builder builderForValue) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder addAllPhone(
              Iterable<? extends PhoneNumber> values) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
                  values, phone_);
          onChanged();
        } else {
          phoneBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder clearPhone() {
        if (phoneBuilder_ == null) {
          phone_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          phoneBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public Builder removePhone(int index) {
        if (phoneBuilder_ == null) {
          ensurePhoneIsMutable();
          phone_.remove(index);
          onChanged();
        } else {
          phoneBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public PhoneNumber.Builder getPhoneBuilder(
              int index) {
        return getPhoneFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public PhoneNumberOrBuilder getPhoneOrBuilder(
              int index) {
        if (phoneBuilder_ == null) {
          return phone_.get(index);
        } else {
          return phoneBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public java.util.List<? extends PhoneNumberOrBuilder>
      getPhoneOrBuilderList() {
        if (phoneBuilder_ != null) {
          return phoneBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phone_);
        }
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public PhoneNumber.Builder addPhoneBuilder() {
        return getPhoneFieldBuilder().addBuilder(
                PhoneNumber.getDefaultInstance());
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public PhoneNumber.Builder addPhoneBuilder(
              int index) {
        return getPhoneFieldBuilder().addBuilder(
                index, PhoneNumber.getDefaultInstance());
      }

      /**
       * <code>repeated .model.Person.PhoneNumber phone = 4;</code>
       */
      public java.util.List<PhoneNumber.Builder>
      getPhoneBuilderList() {
        return getPhoneFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilder<
              PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>
      getPhoneFieldBuilder() {
        if (phoneBuilder_ == null) {
          phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                  PhoneNumber, PhoneNumber.Builder, PhoneNumberOrBuilder>(
                  phone_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          phone_ = null;
        }
        return phoneBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:model.Person)
    }

    // @@protoc_insertion_point(class_scope:model.Person)
  }

  // @@protoc_insertion_point(outer_class_scope)
}
